<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>SOURCE.yaml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~Y</string>
	<key>name</key>
	<string>YAML Bundle Source</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.yaml_bundle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(?&lt;=\s|^) (\#) (?!\{) .* $\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.yaml_bundle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)(
			  foldingStartMarker |
			  foldingStopMarker |
			  match |
			  begin |
			  end
			) (\:) [ ] \| $
			</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.yaml_bundle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.regexp.oniguruma.yaml_bundle</string>
			<key>end</key>
			<string>(?x)^ (?= \s* \w+ \:)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp.oniguruma</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.file.yaml_bundle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)^(\S+?) (\:) \s* $
			</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.yaml_bundle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?x)(\s) (
			  patterns |
			  captures |
			  beginCaptures |
			  endCaptures |
			  settings |
			  shellVariables
			) (\:) \s* $
			</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)(
			  foldingStartMarker |
			  foldingStopMarker |
			  match |
			  begin |
			  end |
			  symbolTransformation
			) (\:)
			</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.yaml_bundle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.regexp.oniguruma.yaml_bundle</string>
			<key>end</key>
			<string>(?x)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.regexp.oniguruma</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)( uuid |
			  scopeName |
			  keyEquivalent |
			  name |
			  contentName |
			  include |
			  scope |
			  value |
			  input |
			  output |
			  command |
			  showInSymbolList )
			(\:)
			</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.yaml_bundle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.yaml_bundle</string>
			<key>end</key>
			<string>(?x)(?= [\]\}\s]* $ )</string>
			<key>name</key>
			<string>meta.value-pair.yaml_bundle</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?x)( patterns |
			  fileTypes )
			(\:) \s+ (\[)
			</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.yaml_bundle</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.key-value.yaml_bundle</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.yaml_bundle</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>inline-array.yaml_bundle</string>
			<key>end</key>
			<string>(?x)(\]) \s* $</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.array.yaml_bundle</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.value-pair.yaml_bundle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.yaml_bundle</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?x)\'</string>
					<key>end</key>
					<string>(?x)\'</string>
					<key>name</key>
					<string>string.quoted.single.yaml_bundle</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yaml_bundle</string>
	<key>uuid</key>
	<string>4B8FDF89-E042-46A8-9B41-DC7A3EBB335E</string>
</dict>
</plist>
